# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_flatten_3d_rowmajor <- function(arr, d1, d2, d3) {
    .Call(`_tulpaRatio_cpp_flatten_3d_rowmajor`, arr, d1, d2, d3)
}

cpp_sample_crt <- function(y, r) {
    .Call(`_tulpaRatio_cpp_sample_crt`, y, r)
}

cpp_sample_crt_sum <- function(y, r) {
    .Call(`_tulpaRatio_cpp_sample_crt_sum`, y, r)
}

cpp_crt_mean <- function(y, r) {
    .Call(`_tulpaRatio_cpp_crt_mean`, y, r)
}

cpp_ess_fit <- function(q_init, y_num, y_denom, y_denom_cont, X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, prior_params, zi_params, latent_params, st_params, n_iter, n_warmup, seed, verbose) {
    .Call(`_tulpaRatio_cpp_ess_fit`, q_init, y_num, y_denom, y_denom_cont, X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, prior_params, zi_params, latent_params, st_params, n_iter, n_warmup, seed, verbose)
}

cpp_ess_get_n_params <- function(X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, zi_params) {
    .Call(`_tulpaRatio_cpp_ess_get_n_params`, X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, zi_params)
}

cpp_gibbs_spatial <- function(data_list) {
    .Call(`_tulpaRatio_cpp_gibbs_spatial`, data_list)
}

cpp_gpu_available <- function() {
    .Call(`_tulpaRatio_cpp_gpu_available`)
}

cpp_gpu_info <- function() {
    .Call(`_tulpaRatio_cpp_gpu_info`)
}

cpp_hmc_fit <- function(q_init, y_num, y_denom, y_num_cont, y_denom_cont, X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, prior_params, zi_params, latent_params, st_params, tvc_params, svc_params, n_iter, n_warmup, L, n_chains, seed, n_threads, verbose, gradient_mode_str = "auto", max_treedepth = 10L, metric_str = "auto", adapt_delta = -1.0, riemannian = 0L, n_cores = 0L) {
    .Call(`_tulpaRatio_cpp_hmc_fit`, q_init, y_num, y_denom, y_num_cont, y_denom_cont, X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, prior_params, zi_params, latent_params, st_params, tvc_params, svc_params, n_iter, n_warmup, L, n_chains, seed, n_threads, verbose, gradient_mode_str, max_treedepth, metric_str, adapt_delta, riemannian, n_cores)
}

cpp_get_max_threads <- function() {
    .Call(`_tulpaRatio_cpp_get_max_threads`)
}

cpp_hmc_fit_gp <- function(q_init, y_num, y_denom, y_denom_cont, X_num, X_denom, re_params, model_type_str, gp_params, ms_gp_params, ms_temporal_params, rsr_params, temporal_params, latent_params, st_params, tvc_params, svc_params, sigma_beta, sigma_re_scale, phi_prior_shape, phi_prior_rate, zi_type_str, X_zi, zi_prior_sd, n_iter, n_warmup, L, n_chains, seed, n_threads, verbose, max_treedepth = 10L, adapt_delta = -1.0, metric_str = "auto", gradient_mode_str = "auto") {
    .Call(`_tulpaRatio_cpp_hmc_fit_gp`, q_init, y_num, y_denom, y_denom_cont, X_num, X_denom, re_params, model_type_str, gp_params, ms_gp_params, ms_temporal_params, rsr_params, temporal_params, latent_params, st_params, tvc_params, svc_params, sigma_beta, sigma_re_scale, phi_prior_shape, phi_prior_rate, zi_type_str, X_zi, zi_prior_sd, n_iter, n_warmup, L, n_chains, seed, n_threads, verbose, max_treedepth, adapt_delta, metric_str, gradient_mode_str)
}

cpp_hmc_fit_gp_v2 <- function(args) {
    .Call(`_tulpaRatio_cpp_hmc_fit_gp_v2`, args)
}

cpp_kriging_predict <- function(coords_train, coords_new, w_train, sigma2, phi, cov_type, nn) {
    .Call(`_tulpaRatio_cpp_kriging_predict`, coords_train, coords_new, w_train, sigma2, phi, cov_type, nn)
}

cpp_pg_binomial_gibbs <- function(y, n, X, group, n_groups, n_iter = 2000L, n_warmup = 1000L, thin = 1L, prior_beta_sd = 10.0, prior_sigma_scale = 2.5, store_eta = FALSE, verbose = TRUE, n_threads = 1L) {
    .Call(`_tulpaRatio_cpp_pg_binomial_gibbs`, y, n, X, group, n_groups, n_iter, n_warmup, thin, prior_beta_sd, prior_sigma_scale, store_eta, verbose, n_threads)
}

cpp_pg_get_max_threads <- function() {
    .Call(`_tulpaRatio_cpp_pg_get_max_threads`)
}

cpp_pg_binomial_gibbs_spatial <- function(y, n, X, re_group, n_re_groups, spatial_group, n_spatial_units, adj_list, n_neighbors, n_iter = 2000L, n_warmup = 1000L, thin = 1L, prior_beta_sd = 10.0, prior_sigma_re_scale = 2.5, prior_tau_shape = 1.0, prior_tau_rate = 0.01, store_eta = FALSE, verbose = TRUE, n_threads = 1L) {
    .Call(`_tulpaRatio_cpp_pg_binomial_gibbs_spatial`, y, n, X, re_group, n_re_groups, spatial_group, n_spatial_units, adj_list, n_neighbors, n_iter, n_warmup, thin, prior_beta_sd, prior_sigma_re_scale, prior_tau_shape, prior_tau_rate, store_eta, verbose, n_threads)
}

cpp_pg_binomial_gibbs_bym2 <- function(y, n, X, re_group, n_re_groups, spatial_group, n_spatial_units, adj_list, n_neighbors, scale_factor, n_iter = 2000L, n_warmup = 1000L, thin = 1L, prior_beta_sd = 10.0, prior_sigma_re_scale = 2.5, prior_sigma_spatial_scale = 2.5, prior_rho_alpha = 0.5, prior_rho_beta = 0.5, store_eta = FALSE, verbose = TRUE, n_threads = 1L) {
    .Call(`_tulpaRatio_cpp_pg_binomial_gibbs_bym2`, y, n, X, re_group, n_re_groups, spatial_group, n_spatial_units, adj_list, n_neighbors, scale_factor, n_iter, n_warmup, thin, prior_beta_sd, prior_sigma_re_scale, prior_sigma_spatial_scale, prior_rho_alpha, prior_rho_beta, store_eta, verbose, n_threads)
}

cpp_pg_nngp_conditional_probe <- function(i, w, sigma2, phi_gp, cov_type, coords, nn_idx, nn_dist, nn_order, nn) {
    .Call(`_tulpaRatio_cpp_pg_nngp_conditional_probe`, i, w, sigma2, phi_gp, cov_type, coords, nn_idx, nn_dist, nn_order, nn)
}

cpp_pg_nngp_log_density_probe <- function(w, sigma2, phi_gp, cov_type, coords, nn_idx, nn_dist, nn_order, nn) {
    .Call(`_tulpaRatio_cpp_pg_nngp_log_density_probe`, w, sigma2, phi_gp, cov_type, coords, nn_idx, nn_dist, nn_order, nn)
}

cpp_pg_binomial_gibbs_gp <- function(y, n, X, re_group, n_re_groups, coords, nn_idx, nn_dist, nn_order, obs_to_loc, n_spatial, nn, sigma2_gp_init, phi_gp_init, cov_type, n_iter = 2000L, n_warmup = 1000L, thin = 1L, prior_beta_sd = 10.0, prior_sigma_re_scale = 2.5, prior_sigma_gp_U = 1.0, prior_sigma_gp_alpha = 0.01, prior_phi_lower = 0.01, prior_phi_upper = 10.0, store_eta = FALSE, verbose = TRUE, n_threads = 1L) {
    .Call(`_tulpaRatio_cpp_pg_binomial_gibbs_gp`, y, n, X, re_group, n_re_groups, coords, nn_idx, nn_dist, nn_order, obs_to_loc, n_spatial, nn, sigma2_gp_init, phi_gp_init, cov_type, n_iter, n_warmup, thin, prior_beta_sd, prior_sigma_re_scale, prior_sigma_gp_U, prior_sigma_gp_alpha, prior_phi_lower, prior_phi_upper, store_eta, verbose, n_threads)
}

cpp_pg_binomial_gibbs_temporal <- function(y, n, X, re_group, n_re_groups, time_idx, n_times, seasonal_period, trend_type, short_type, n_iter = 2000L, n_warmup = 1000L, thin = 1L, prior_beta_sd = 10.0, prior_sigma_re_scale = 2.5, prior_sigma_trend_scale = 1.0, prior_sigma_seasonal_scale = 1.0, prior_sigma_short_scale = 1.0, rho_short_init = 0.5, store_eta = FALSE, verbose = TRUE, n_threads = 1L) {
    .Call(`_tulpaRatio_cpp_pg_binomial_gibbs_temporal`, y, n, X, re_group, n_re_groups, time_idx, n_times, seasonal_period, trend_type, short_type, n_iter, n_warmup, thin, prior_beta_sd, prior_sigma_re_scale, prior_sigma_trend_scale, prior_sigma_seasonal_scale, prior_sigma_short_scale, rho_short_init, store_eta, verbose, n_threads)
}

cpp_pg_binomial_gibbs_multiscale_gp <- function(y, n, X, re_group, n_re_groups, coords, nn_idx_local, nn_dist_local, nn_order_local, nn_local, nn_idx_regional, nn_dist_regional, nn_order_regional, nn_regional, obs_to_loc, n_spatial, sigma2_local_init, phi_local_init, sigma2_regional_init, phi_regional_init, cov_type, n_iter = 2000L, n_warmup = 1000L, thin = 1L, prior_beta_sd = 10.0, prior_sigma_re_scale = 2.5, prior_sigma_local_U = 1.0, prior_sigma_local_alpha = 0.01, prior_phi_local_lower = 0.01, prior_phi_local_upper = 5.0, prior_sigma_regional_U = 1.0, prior_sigma_regional_alpha = 0.01, prior_phi_regional_lower = 0.1, prior_phi_regional_upper = 20.0, store_eta = FALSE, verbose = TRUE, n_threads = 1L) {
    .Call(`_tulpaRatio_cpp_pg_binomial_gibbs_multiscale_gp`, y, n, X, re_group, n_re_groups, coords, nn_idx_local, nn_dist_local, nn_order_local, nn_local, nn_idx_regional, nn_dist_regional, nn_order_regional, nn_regional, obs_to_loc, n_spatial, sigma2_local_init, phi_local_init, sigma2_regional_init, phi_regional_init, cov_type, n_iter, n_warmup, thin, prior_beta_sd, prior_sigma_re_scale, prior_sigma_local_U, prior_sigma_local_alpha, prior_phi_local_lower, prior_phi_local_upper, prior_sigma_regional_U, prior_sigma_regional_alpha, prior_phi_regional_lower, prior_phi_regional_upper, store_eta, verbose, n_threads)
}

cpp_pg_binomial_gibbs_rsr <- function(y, n, X, re_group, n_re_groups, spatial_group, n_spatial_units, adj_list, n_neighbors, rsr_projection, rsr_n, n_iter = 2000L, n_warmup = 1000L, thin = 1L, prior_beta_sd = 10.0, prior_sigma_re_scale = 2.5, prior_tau_shape = 1.0, prior_tau_rate = 0.01, store_eta = FALSE, verbose = TRUE, n_threads = 1L) {
    .Call(`_tulpaRatio_cpp_pg_binomial_gibbs_rsr`, y, n, X, re_group, n_re_groups, spatial_group, n_spatial_units, adj_list, n_neighbors, rsr_projection, rsr_n, n_iter, n_warmup, thin, prior_beta_sd, prior_sigma_re_scale, prior_tau_shape, prior_tau_rate, store_eta, verbose, n_threads)
}

cpp_pg_negbin_gibbs <- function(y, X, group, n_groups, n_iter, n_warmup, thin, prior_beta_sd, prior_sigma_scale, prior_r_shape, prior_r_rate, r_init, store_eta, verbose, n_threads) {
    .Call(`_tulpaRatio_cpp_pg_negbin_gibbs`, y, X, group, n_groups, n_iter, n_warmup, thin, prior_beta_sd, prior_sigma_scale, prior_r_shape, prior_r_rate, r_init, store_eta, verbose, n_threads)
}

cpp_pg_negbin_negbin_gibbs <- function(y_num, y_denom, X_num, X_denom, group, n_groups, n_iter, n_warmup, thin, prior_beta_sd, prior_sigma_scale, prior_r_shape, prior_r_rate, r_num_init, r_denom_init, shared, store_eta, verbose, n_threads) {
    .Call(`_tulpaRatio_cpp_pg_negbin_negbin_gibbs`, y_num, y_denom, X_num, X_denom, group, n_groups, n_iter, n_warmup, thin, prior_beta_sd, prior_sigma_scale, prior_r_shape, prior_r_rate, r_num_init, r_denom_init, shared, store_eta, verbose, n_threads)
}

cpp_pg_negbin_gibbs_spatial <- function(y, X, re_group, n_re_groups, spatial_group, n_spatial_units, adj_list, n_neighbors, n_iter, n_warmup, thin, prior_beta_sd, prior_sigma_re_scale, prior_tau_shape, prior_tau_rate, prior_r_shape, prior_r_rate, r_init, store_eta, verbose, n_threads) {
    .Call(`_tulpaRatio_cpp_pg_negbin_gibbs_spatial`, y, X, re_group, n_re_groups, spatial_group, n_spatial_units, adj_list, n_neighbors, n_iter, n_warmup, thin, prior_beta_sd, prior_sigma_re_scale, prior_tau_shape, prior_tau_rate, prior_r_shape, prior_r_rate, r_init, store_eta, verbose, n_threads)
}

cpp_rpg1 <- function(z) {
    .Call(`_tulpaRatio_cpp_rpg1`, z)
}

cpp_rpg <- function(b, z) {
    .Call(`_tulpaRatio_cpp_rpg`, b, z)
}

cpp_sghmc_fit <- function(q_init, y_num, y_denom, y_denom_cont, X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, prior_params, zi_params, latent_params, st_params, n_iter, n_warmup, batch_size, epsilon, alpha, L, seed, verbose) {
    .Call(`_tulpaRatio_cpp_sghmc_fit`, q_init, y_num, y_denom, y_denom_cont, X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, prior_params, zi_params, latent_params, st_params, n_iter, n_warmup, batch_size, epsilon, alpha, L, seed, verbose)
}

cpp_sgld_fit <- function(q_init, y_num, y_denom, y_denom_cont, X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, prior_params, zi_params, latent_params, st_params, n_iter, n_warmup, batch_size, epsilon, schedule_a, schedule_b, schedule_gamma, use_schedule, seed, verbose) {
    .Call(`_tulpaRatio_cpp_sgld_fit`, q_init, y_num, y_denom, y_denom_cont, X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, prior_params, zi_params, latent_params, st_params, n_iter, n_warmup, batch_size, epsilon, schedule_a, schedule_b, schedule_gamma, use_schedule, seed, verbose)
}

cpp_chain_concurrency <- function(n_chains, max_concurrent) {
    .Call(`_tulpaRatio_cpp_chain_concurrency`, n_chains, max_concurrent)
}

cpp_chain_visits <- function(n_chains, max_concurrent) {
    .Call(`_tulpaRatio_cpp_chain_visits`, n_chains, max_concurrent)
}

cpp_set_max_threads <- function(n_threads) {
    invisible(.Call(`_tulpaRatio_cpp_set_max_threads`, n_threads))
}

cpp_within_chain_team <- function(n_chains, max_concurrent, want) {
    .Call(`_tulpaRatio_cpp_within_chain_team`, n_chains, max_concurrent, want)
}

cpp_num_procs <- function() {
    .Call(`_tulpaRatio_cpp_num_procs`)
}

cpp_gradient_fields <- function() {
    .Call(`_tulpaRatio_cpp_gradient_fields`)
}

cpp_gradient_dispatch <- function(field, n_obs = 40L, n_units = 8L, n_times = 5L, seed = 42L, family = "binomial") {
    .Call(`_tulpaRatio_cpp_gradient_dispatch`, field, n_obs, n_units, n_times, seed, family)
}

cpp_gradient_check <- function(field, n_obs = 400L, n_units = 25L, n_times = 10L, eps = 1e-5, seed = 42L, mode = "handcoded", precenter = FALSE, family = "binomial", temporal_shared = TRUE, zi = "none", near_unit_rho = FALSE, n_threads = 1L) {
    .Call(`_tulpaRatio_cpp_gradient_check`, field, n_obs, n_units, n_times, eps, seed, mode, precenter, family, temporal_shared, zi, near_unit_rho, n_threads)
}

cpp_gradient_race <- function(field, n_points = 8L, n_threads = 4L, rounds = 8L, n_obs = 200L, n_units = 16L, n_times = 8L, seed = 42L, family = "binomial", prime_other_model = FALSE) {
    .Call(`_tulpaRatio_cpp_gradient_race`, field, n_points, n_threads, rounds, n_obs, n_units, n_times, seed, family, prime_other_model)
}

cpp_logpost_at <- function(field, n_obs = 400L, n_units = 25L, n_times = 10L, seed = 42L, family = "binomial", temporal_shared = TRUE, zi = "none") {
    .Call(`_tulpaRatio_cpp_logpost_at`, field, n_obs, n_units, n_times, seed, family, temporal_shared, zi)
}

cpp_msgp_nc_coordinate_spread <- function(n_obs = 400L, n_units = 25L, n_draws = 5L, seed = 42L) {
    .Call(`_tulpaRatio_cpp_msgp_nc_coordinate_spread`, n_obs, n_units, n_draws, seed)
}

cpp_ms_temporal_nc_coordinate_spread <- function(field = "ms_temporal_nc", n = 12L, sigma2 = 0.25, n_draws = 6L, seed = 42L, n_groups = 1L) {
    .Call(`_tulpaRatio_cpp_ms_temporal_nc_coordinate_spread`, field, n, sigma2, n_draws, seed, n_groups)
}

cpp_ms_temporal_nc_group_contrast_flat <- function(field = "ms_temporal_nc", n = 12L, n_groups = 3L, sigma2 = 0.25, n_draws = 6L, seed = 42L) {
    .Call(`_tulpaRatio_cpp_ms_temporal_nc_group_contrast_flat`, field, n, n_groups, sigma2, n_draws, seed)
}

cpp_test_leapfrog <- function(q_init, p_init, epsilon, L) {
    .Call(`_tulpaRatio_cpp_test_leapfrog`, q_init, p_init, epsilon, L)
}

cpp_test_hamiltonian <- function(q, p) {
    .Call(`_tulpaRatio_cpp_test_hamiltonian`, q, p)
}

cpp_test_log_sum_exp <- function(log_vals) {
    .Call(`_tulpaRatio_cpp_test_log_sum_exp`, log_vals)
}

cpp_test_softmax <- function(x) {
    .Call(`_tulpaRatio_cpp_test_softmax`, x)
}

cpp_test_inv_logit <- function(x) {
    .Call(`_tulpaRatio_cpp_test_inv_logit`, x)
}

cpp_test_lgamma <- function(x) {
    .Call(`_tulpaRatio_cpp_test_lgamma`, x)
}

cpp_test_poisson_loglik <- function(y, lambda) {
    .Call(`_tulpaRatio_cpp_test_poisson_loglik`, y, lambda)
}

cpp_test_binomial_loglik <- function(y, n, p) {
    .Call(`_tulpaRatio_cpp_test_binomial_loglik`, y, n, p)
}

cpp_test_negbin_loglik <- function(y, mu, phi) {
    .Call(`_tulpaRatio_cpp_test_negbin_loglik`, y, mu, phi)
}

cpp_test_normal_loglik <- function(y, mu, sigma) {
    .Call(`_tulpaRatio_cpp_test_normal_loglik`, y, mu, sigma)
}

cpp_test_cholesky <- function(A) {
    .Call(`_tulpaRatio_cpp_test_cholesky`, A)
}

cpp_test_matvec <- function(A, x) {
    .Call(`_tulpaRatio_cpp_test_matvec`, A, x)
}

cpp_test_autodiff_gradient <- function(x_vals) {
    .Call(`_tulpaRatio_cpp_test_autodiff_gradient`, x_vals)
}

cpp_test_autodiff_exp_chain <- function(x_val) {
    .Call(`_tulpaRatio_cpp_test_autodiff_exp_chain`, x_val)
}

cpp_test_autodiff_log_likelihood <- function(y, eta) {
    .Call(`_tulpaRatio_cpp_test_autodiff_log_likelihood`, y, eta)
}

cpp_test_autodiff_division <- function(a_val, b_val) {
    .Call(`_tulpaRatio_cpp_test_autodiff_division`, a_val, b_val)
}

cpp_test_autodiff_lgamma <- function(x_val) {
    .Call(`_tulpaRatio_cpp_test_autodiff_lgamma`, x_val)
}

cpp_test_autodiff_softplus <- function(x_val) {
    .Call(`_tulpaRatio_cpp_test_autodiff_softplus`, x_val)
}

cpp_test_autodiff_inv_logit <- function(x_val) {
    .Call(`_tulpaRatio_cpp_test_autodiff_inv_logit`, x_val)
}

cpp_test_autodiff_log <- function(x_val) {
    .Call(`_tulpaRatio_cpp_test_autodiff_log`, x_val)
}

cpp_test_autodiff_sqrt <- function(x_val) {
    .Call(`_tulpaRatio_cpp_test_autodiff_sqrt`, x_val)
}

cpp_test_autodiff_pow <- function(x_val, p) {
    .Call(`_tulpaRatio_cpp_test_autodiff_pow`, x_val, p)
}

cpp_test_autodiff_log1p <- function(x_val) {
    .Call(`_tulpaRatio_cpp_test_autodiff_log1p`, x_val)
}

cpp_test_autodiff_log_sum_exp <- function(a_val, b_val) {
    .Call(`_tulpaRatio_cpp_test_autodiff_log_sum_exp`, a_val, b_val)
}

cpp_test_autodiff_logit <- function(x_val) {
    .Call(`_tulpaRatio_cpp_test_autodiff_logit`, x_val)
}

cpp_test_autodiff_negbin_loglik <- function(y, mu, phi) {
    .Call(`_tulpaRatio_cpp_test_autodiff_negbin_loglik`, y, mu, phi)
}

cpp_test_pg_update_beta <- function(kappa, omega, X, re_contrib, prior_sd) {
    .Call(`_tulpaRatio_cpp_test_pg_update_beta`, kappa, omega, X, re_contrib, prior_sd)
}

cpp_test_pg_update_re <- function(kappa, omega, X_beta, group, n_groups, sigma_re) {
    .Call(`_tulpaRatio_cpp_test_pg_update_re`, kappa, omega, X_beta, group, n_groups, sigma_re)
}

cpp_test_pg_update_sigma_re <- function(re, scale) {
    .Call(`_tulpaRatio_cpp_test_pg_update_sigma_re`, re, scale)
}

cpp_test_dot_product <- function(x, y) {
    .Call(`_tulpaRatio_cpp_test_dot_product`, x, y)
}

cpp_test_norm_squared <- function(x) {
    .Call(`_tulpaRatio_cpp_test_norm_squared`, x)
}

cpp_test_vector_sum <- function(x) {
    .Call(`_tulpaRatio_cpp_test_vector_sum`, x)
}

cpp_test_axpy <- function(a, x, y) {
    .Call(`_tulpaRatio_cpp_test_axpy`, a, x, y)
}

cpp_test_scale <- function(a, x) {
    .Call(`_tulpaRatio_cpp_test_scale`, a, x)
}

cpp_test_linalg_matvec <- function(X, beta) {
    .Call(`_tulpaRatio_cpp_test_linalg_matvec`, X, beta)
}

cpp_test_linalg_matvec_add <- function(X, beta, y_init) {
    .Call(`_tulpaRatio_cpp_test_linalg_matvec_add`, X, beta, y_init)
}

cpp_test_linalg_matvec_transpose <- function(X, x) {
    .Call(`_tulpaRatio_cpp_test_linalg_matvec_transpose`, X, x)
}

cpp_test_sparse_laplacian_quadform <- function(row_ptr, col_idx, x) {
    .Call(`_tulpaRatio_cpp_test_sparse_laplacian_quadform`, row_ptr, col_idx, x)
}

cpp_test_linalg_log_sum_exp <- function(a, b) {
    .Call(`_tulpaRatio_cpp_test_linalg_log_sum_exp`, a, b)
}

cpp_test_linalg_log_sum_exp_vec <- function(x) {
    .Call(`_tulpaRatio_cpp_test_linalg_log_sum_exp_vec`, x)
}

cpp_test_softmax_inplace <- function(x) {
    .Call(`_tulpaRatio_cpp_test_softmax_inplace`, x)
}

cpp_test_compute_linear_predictors <- function(X_num, beta_num, X_denom, beta_denom, n_threads) {
    .Call(`_tulpaRatio_cpp_test_compute_linear_predictors`, X_num, beta_num, X_denom, beta_denom, n_threads)
}

cpp_test_rw1_quadratic_form <- function(phi, cyclic) {
    .Call(`_tulpaRatio_cpp_test_rw1_quadratic_form`, phi, cyclic)
}

cpp_test_rw2_quadratic_form <- function(phi, cyclic) {
    .Call(`_tulpaRatio_cpp_test_rw2_quadratic_form`, phi, cyclic)
}

cpp_test_ar1_log_density <- function(phi, rho, tau) {
    .Call(`_tulpaRatio_cpp_test_ar1_log_density`, phi, rho, tau)
}

cpp_test_temporal_log_prior <- function(phi, type_str, tau, rho, cyclic) {
    .Call(`_tulpaRatio_cpp_test_temporal_log_prior`, phi, type_str, tau, rho, cyclic)
}

cpp_test_ms_rw_log_lik <- function(phi, sigma2, order, cyclic, augment) {
    .Call(`_tulpaRatio_cpp_test_ms_rw_log_lik`, phi, sigma2, order, cyclic, augment)
}

cpp_test_log1pexp <- function(x) {
    .Call(`_tulpaRatio_cpp_test_log1pexp`, x)
}

cpp_test_zi_logistic <- function(x) {
    .Call(`_tulpaRatio_cpp_test_zi_logistic`, x)
}

cpp_test_log_logistic <- function(x) {
    .Call(`_tulpaRatio_cpp_test_log_logistic`, x)
}

cpp_test_log1m_logistic <- function(x) {
    .Call(`_tulpaRatio_cpp_test_log1m_logistic`, x)
}

cpp_test_zi_poisson_lpmf <- function(y, mu) {
    .Call(`_tulpaRatio_cpp_test_zi_poisson_lpmf`, y, mu)
}

cpp_test_zi_negbin_lpmf <- function(y, mu, phi) {
    .Call(`_tulpaRatio_cpp_test_zi_negbin_lpmf`, y, mu, phi)
}

cpp_test_zi_poisson_lpmf_logit <- function(y, mu, logit_zi) {
    .Call(`_tulpaRatio_cpp_test_zi_poisson_lpmf_logit`, y, mu, logit_zi)
}

cpp_test_zi_negbin_lpmf_logit <- function(y, mu, phi, logit_zi) {
    .Call(`_tulpaRatio_cpp_test_zi_negbin_lpmf_logit`, y, mu, phi, logit_zi)
}

cpp_test_truncated_poisson_lpmf <- function(y, mu) {
    .Call(`_tulpaRatio_cpp_test_truncated_poisson_lpmf`, y, mu)
}

cpp_test_truncated_negbin_lpmf <- function(y, mu, phi) {
    .Call(`_tulpaRatio_cpp_test_truncated_negbin_lpmf`, y, mu, phi)
}

cpp_test_hurdle_poisson_lpmf_logit <- function(y, mu, logit_theta) {
    .Call(`_tulpaRatio_cpp_test_hurdle_poisson_lpmf_logit`, y, mu, logit_theta)
}

cpp_test_hurdle_negbin_lpmf_logit <- function(y, mu, phi, logit_theta) {
    .Call(`_tulpaRatio_cpp_test_hurdle_negbin_lpmf_logit`, y, mu, phi, logit_theta)
}

cpp_test_zi_log_likelihood <- function(y, mu, phi, logit_zi, zi_type_str) {
    .Call(`_tulpaRatio_cpp_test_zi_log_likelihood`, y, mu, phi, logit_zi, zi_type_str)
}

cpp_test_zi_poisson_grad_logit_zi <- function(y, mu, logit_zi) {
    .Call(`_tulpaRatio_cpp_test_zi_poisson_grad_logit_zi`, y, mu, logit_zi)
}

cpp_test_zi_negbin_grad_logit_zi <- function(y, mu, phi, logit_zi) {
    .Call(`_tulpaRatio_cpp_test_zi_negbin_grad_logit_zi`, y, mu, phi, logit_zi)
}

cpp_test_hurdle_grad_logit_theta <- function(y, logit_theta) {
    .Call(`_tulpaRatio_cpp_test_hurdle_grad_logit_theta`, y, logit_theta)
}

cpp_test_get_max_threads <- function() {
    .Call(`_tulpaRatio_cpp_test_get_max_threads`)
}

cpp_test_parallel_dot_products <- function(X, y, n_threads) {
    .Call(`_tulpaRatio_cpp_test_parallel_dot_products`, X, y, n_threads)
}

cpp_test_parallel_likelihood <- function(y, mu, n_threads) {
    .Call(`_tulpaRatio_cpp_test_parallel_likelihood`, y, mu, n_threads)
}

cpp_test_parallel_independent <- function(n, n_threads) {
    .Call(`_tulpaRatio_cpp_test_parallel_independent`, n, n_threads)
}

cpp_test_st_gp_log_lik <- function(w, sigma2, phi_space, phi_time, coords, time_values, nn, nn_idx, nn_dist_space, nn_dist_time, nn_order, nonsep_type = "product", cov_space = "exponential", cov_time = "exponential") {
    .Call(`_tulpaRatio_cpp_test_st_gp_log_lik`, w, sigma2, phi_space, phi_time, coords, time_values, nn, nn_idx, nn_dist_space, nn_dist_time, nn_order, nonsep_type, cov_space, cov_time)
}

cpp_tls_workspace_shrink <- function(cycles, work, n) {
    .Call(`_tulpaRatio_cpp_tls_workspace_shrink`, cycles, work, n)
}

cpp_tulpa_abi_version <- function() {
    .Call(`_tulpaRatio_cpp_tulpa_abi_version`)
}

cpp_tulpa_compiled_abi_version <- function() {
    .Call(`_tulpaRatio_cpp_tulpa_compiled_abi_version`)
}

cpp_tulpa_runtime_abi_version <- function() {
    .Call(`_tulpaRatio_cpp_tulpa_runtime_abi_version`)
}

cpp_tulpa_pg_binomial_gibbs <- function(y, n, X, group, n_groups, n_iter = 2000L, n_warmup = 1000L, thin = 1L, prior_beta_sd = 10.0, prior_sigma_scale = 2.5, store_eta = FALSE, verbose = TRUE, n_threads = 1L) {
    .Call(`_tulpaRatio_cpp_tulpa_pg_binomial_gibbs`, y, n, X, group, n_groups, n_iter, n_warmup, thin, prior_beta_sd, prior_sigma_scale, store_eta, verbose, n_threads)
}

cpp_tulpaRatio_run_nuts_specs <- function(y_num, y_denom, y_num_cont, y_denom_cont, X_list, cfg_list, init, n_iter, n_warmup, max_treedepth = 10L, adapt_delta = 0.8, seed = 1L, verbose = FALSE, gradient_mode = "A_r", sigma_beta = 2.5, phi_prior_shape = 1.0, phi_prior_rate = 0.01, sigma_prior_scale = 1.0, re_params, spatial_params, temporal_params) {
    .Call(`_tulpaRatio_cpp_tulpaRatio_run_nuts_specs`, y_num, y_denom, y_num_cont, y_denom_cont, X_list, cfg_list, init, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose, gradient_mode, sigma_beta, phi_prior_shape, phi_prior_rate, sigma_prior_scale, re_params, spatial_params, temporal_params)
}

cpp_vi_fit <- function(q_init, y_num, y_denom, y_denom_cont, X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, prior_params, zi_params, latent_params, st_params, vi_options, verbose = TRUE) {
    .Call(`_tulpaRatio_cpp_vi_fit`, q_init, y_num, y_denom, y_denom_cont, X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, prior_params, zi_params, latent_params, st_params, vi_options, verbose)
}

cpp_vi_get_n_params <- function(X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, zi_params) {
    .Call(`_tulpaRatio_cpp_vi_get_n_params`, X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, zi_params)
}

